name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MKDocs
        run: pip install mkdocs

      - name: Install MKDocs Theme
        run: pip install mkdocs-gitbook

      - name: Deploy the docs
        run: mkdocs gh-deploy -f douro_data_docs/mkdocs.yml
